---
title: "Week7_code"
author: "Kimberly Than"
date: "October 4, 2017"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r test1}

test1 = "The current year is 2016"

# Pattern for finding any digit in the variable test1
my_pattern = "[zxq]" # Returns FALSE
my_pattern = "[0-9]" # Returns TRUE
# grepl(pattern, x) to return logical vector (TRUE OR FALSE)
grepl(pattern = my_pattern, test1)

# Exercise 2
temp = gregexpr(my_pattern, test1)
string_position = temp[[1]]

# console: substr(test1, 21,24)
# console: substr(test1, string_position[1], string_position[length(string_position)])

gregexpr("[[:blank:]]", test1)

# Exercise 3
grepl(pattern = "[[:upper:][:digit:]]", test1)

# Exercise 4
temp1 = regexpr(pattern = "[[:blank:]]", test1)
first_space = temp[[1]][1] # the first entire of the first slot

# Exercise 5
my_pattern = "[[:lower:]].[[:digit:]]"
grepl(my_pattern, test1)

# Exercise 6
gregexpr(my_pattern, test1)
# Or if you don't want the other information 
gregexpr(my_pattern, test1)[[1]][1]

# Exercise 7
my_pattern = "\\s[[:lower:]][[:lower:]]\\s"
loc = gregexpr(my_pattern, test1)[[1]][1]

# Exercise 8 
my_pattern = "is"
test2 = sub(my_pattern, replacement = " is not " , test1)

my_pattern = "\\s[[:lower:]]{2}\\s"
gregexpr(my_pattern, test1)[[1]][1]

# Exercise 9
my_pattern = "\\d{4}"
temp = gregexpr(my_pattern, test2)
string_pos4 = temp[[1]][1]

# Exercise 10
substr(test2, start = string_pos4, stop = string_pos4+1)

```
```{r HW7}
df = read.csv('../data/california-state-university-2015.csv')
df$Employee.Name = as.character(df$Employee.Name)

df$Employee.Name[grepl(pattern = "William", df$Employee.Name)]

```